/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asmedit.gui;

import asmedit.machine.MachineConfig;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author koukola
 */
public class BootSettingsWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BootSettingsWindow.class.getName());

    
    
    protected MachineConfig config;
    
    /**
     * Creates new form BootSettingsWindow
     */
    public BootSettingsWindow() {
        initComponents();
        
    }
    
    public BootSettingsWindow(MachineConfig config) {
        
        initComponents();
        
        this.config = config;
        this.bootAddress.setValue(config.getBootAddress());
        this.interruptAddress.setValue(config.getInterruptAddress());
        this.memoryImageFile.setText(config.getDefaultMemoryFile());
        this.virtualMemoryImageFile.setText(config.getDefaultVirtualMemoryFile());
        this.pageTableAddress.setValue(config.getPageTableAddress());
        this.checkBox.setSelected(!config.getDefaultVirtualMemoryFile().equals(""));
        checkBoxActionPerformed(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bootAddress = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        interruptAddress = new javax.swing.JSpinner();
        checkBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        pageTableAddress = new javax.swing.JSpinner();
        okButton = new javax.swing.JButton();
        chooseMemoryFile = new javax.swing.JButton();
        chooseVirtualMemoryFile = new javax.swing.JButton();
        virtualMemoryImageFile = new javax.swing.JLabel();
        memoryImageFile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Boot address:");

        jLabel2.setText("Interrupt address:");

        jLabel3.setText("Memory image file:");

        checkBox.setText("Add virtual memory space");
        checkBox.addActionListener(this::checkBoxActionPerformed);

        jLabel4.setText("Memory image file:");
        jLabel4.setEnabled(false);

        jLabel5.setText("Page table addr.:");
        jLabel5.setEnabled(false);

        pageTableAddress.setEnabled(false);

        okButton.setText("OK");
        okButton.addActionListener(this::okButtonActionPerformed);

        chooseMemoryFile.setText("Choose");
        chooseMemoryFile.addActionListener(this::chooseMemoryFileActionPerformed);

        chooseVirtualMemoryFile.setText("Choose");
        chooseVirtualMemoryFile.setEnabled(false);
        chooseVirtualMemoryFile.addActionListener(this::chooseVirtualMemoryFileActionPerformed);

        virtualMemoryImageFile.setText("Path...");
        virtualMemoryImageFile.setEnabled(false);

        memoryImageFile.setText("Path...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBox)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(okButton)
                                    .addComponent(pageTableAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chooseVirtualMemoryFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(virtualMemoryImageFile, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chooseMemoryFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memoryImageFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bootAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(interruptAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bootAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(interruptAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chooseMemoryFile)
                    .addComponent(memoryImageFile))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(checkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(chooseVirtualMemoryFile)
                    .addComponent(virtualMemoryImageFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pageTableAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        if (checkBox.isSelected()) {
            chooseVirtualMemoryFile.setEnabled(true);
            virtualMemoryImageFile.setEnabled(true);
            pageTableAddress.setEnabled(true);
            jLabel4.setEnabled(true);
            jLabel5.setEnabled(true);
        } else {
            chooseVirtualMemoryFile.setEnabled(false);
            virtualMemoryImageFile.setEnabled(false);
            pageTableAddress.setEnabled(false);
            jLabel4.setEnabled(false);
            jLabel5.setEnabled(false);
        }
    }//GEN-LAST:event_checkBoxActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        config.setBootAddress((Integer)bootAddress.getValue());
        config.setInterruptAddress((Integer)interruptAddress.getValue());
        config.setPageTableAddress((Integer)pageTableAddress.getValue());
        
        
        
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void chooseMemoryFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseMemoryFileActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        
        File f = fc.getSelectedFile();
        

        
        config.setDefaultMemoryFile(f.getPath());
     
        
        
        
        this.memoryImageFile.setText(f.getPath());
        
    }//GEN-LAST:event_chooseMemoryFileActionPerformed

    private void chooseVirtualMemoryFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseVirtualMemoryFileActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        
        File f = fc.getSelectedFile();
        

        
            
        config.setDefaultVirtualMemoryFile(f.getPath());
     
        
        this.virtualMemoryImageFile.setText(f.getPath());
    }//GEN-LAST:event_chooseVirtualMemoryFileActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BootSettingsWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner bootAddress;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JButton chooseMemoryFile;
    private javax.swing.JButton chooseVirtualMemoryFile;
    private javax.swing.JSpinner interruptAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel memoryImageFile;
    private javax.swing.JButton okButton;
    private javax.swing.JSpinner pageTableAddress;
    private javax.swing.JLabel virtualMemoryImageFile;
    // End of variables declaration//GEN-END:variables
}
