/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asmedit.gui;

import asmedit.gui.devices.ConsoleDeviceWindow;
import asmedit.gui.devices.DeviceFactory;
import asmedit.machine.Device;
import asmedit.machine.Machine;
import asmedit.machine.Register;
import asmedit.machine.devices.ConsoleDevice;
import asmedit.machine.devices.KeyboardDevice;
import asmedit.machine.devices.TextOutputDevice;
import asmedit.utils.TranslationTableGenerator;
import java.awt.event.FocusEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeSupport;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.lang.reflect.Constructor;
import java.util.Scanner;
import javax.swing.BoxLayout;
import javax.swing.JMenuItem;
import javax.swing.SwingWorker;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author koukola
 */
public class MachineWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MachineWindow.class.getName());

    /**
     * Creates new form MachineWindow
     */
    public MachineWindow() {
        
        this.machine = new Machine();
        this.machine.addListener(e -> changeState(e));
          
        this.memWindow = new MemoryWindow(machine.getMemory());
        
        initComponents();
        
        initGeneralRegisters();
        initSystemGeneralRegisters();
        initDevicesMenu();
        
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDeviceMenu = new javax.swing.JPopupMenu();
        registersPanel = new javax.swing.JPanel();
        systemRegistersPanel = new javax.swing.JPanel();
        bootSettingsButton = new javax.swing.JButton();
        bootButton = new javax.swing.JButton();
        stepButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        addDeviceButton = new javax.swing.JButton();
        showMemoryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout registersPanelLayout = new javax.swing.GroupLayout(registersPanel);
        registersPanel.setLayout(registersPanelLayout);
        registersPanelLayout.setHorizontalGroup(
            registersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        registersPanelLayout.setVerticalGroup(
            registersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout systemRegistersPanelLayout = new javax.swing.GroupLayout(systemRegistersPanel);
        systemRegistersPanel.setLayout(systemRegistersPanelLayout);
        systemRegistersPanelLayout.setHorizontalGroup(
            systemRegistersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        systemRegistersPanelLayout.setVerticalGroup(
            systemRegistersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        bootSettingsButton.setText("Boot options");
        bootSettingsButton.addActionListener(this::bootSettingsButtonActionPerformed);

        bootButton.setText("Boot");
        bootButton.addActionListener(this::bootButtonActionPerformed);

        stepButton.setText("Step");
        stepButton.setEnabled(false);
        stepButton.addActionListener(this::stepButtonActionPerformed);

        runButton.setText("Run");
        runButton.setEnabled(false);
        runButton.addActionListener(this::runButtonActionPerformed);

        pauseButton.setText("Pause");
        pauseButton.setEnabled(false);
        pauseButton.addActionListener(this::pauseButtonActionPerformed);

        stopButton.setText("Stop");
        stopButton.setEnabled(false);
        stopButton.addActionListener(this::stopButtonActionPerformed);

        addDeviceButton.setText("Add device");
        addDeviceButton.addActionListener(this::addDeviceButtonActionPerformed);

        showMemoryButton.setText("Show memory");
        showMemoryButton.addActionListener(this::showMemoryButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bootSettingsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pauseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showMemoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(addDeviceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(systemRegistersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bootSettingsButton)
                            .addComponent(bootButton)
                            .addComponent(stepButton)
                            .addComponent(runButton)
                            .addComponent(pauseButton)
                            .addComponent(stopButton))
                        .addGap(52, 52, 52)
                        .addComponent(addDeviceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showMemoryButton))
                    .addComponent(registersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(systemRegistersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bootSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bootSettingsButtonActionPerformed
        new BootSettingsWindow(machine.getConfig()).setVisible(true);
    }//GEN-LAST:event_bootSettingsButtonActionPerformed

    private void bootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bootButtonActionPerformed
        
        
        machine.startAndBoot();
    }//GEN-LAST:event_bootButtonActionPerformed

    private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepButtonActionPerformed
        machine.nextCycle();
    }//GEN-LAST:event_stepButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        
        
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                machine.run();
                return null;
            }
        }.execute();
    }//GEN-LAST:event_runButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        
        runButton.setEnabled(true);
        stepButton.setEnabled(true);
        pauseButton.setEnabled(false);
        
        machine.pause();
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        // TODO add your handling code here:
        
        
        machine.stop();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void addDeviceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeviceButtonActionPerformed
        
        
        addDeviceMenu.show(addDeviceButton, 10, 20);
    }//GEN-LAST:event_addDeviceButtonActionPerformed

    private void showMemoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMemoryButtonActionPerformed
        
        memWindow.setVisible(true);
    }//GEN-LAST:event_showMemoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MachineWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDeviceButton;
    private javax.swing.JPopupMenu addDeviceMenu;
    private javax.swing.JButton bootButton;
    private javax.swing.JButton bootSettingsButton;
    private javax.swing.JButton pauseButton;
    private javax.swing.JPanel registersPanel;
    private javax.swing.JButton runButton;
    private javax.swing.JButton showMemoryButton;
    private javax.swing.JButton stepButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JPanel systemRegistersPanel;
    // End of variables declaration//GEN-END:variables

    
    private void initGeneralRegisters() {
        
        registersPanel.setLayout(new BoxLayout(registersPanel, BoxLayout.Y_AXIS));
        
        int c = 0;
        for (Register r: machine.getRegisters()) {
            RegisterView rv = new RegisterView("r" + c, r);
            registersPanel.add(rv);
            
            c += 1;    
        }
    }
    
    private void initSystemGeneralRegisters() {
        systemRegistersPanel.setLayout(new BoxLayout(systemRegistersPanel, BoxLayout.Y_AXIS));
        
        RegisterView pcv = new RegisterView("pc", machine.getPc());
        
        systemRegistersPanel.add(pcv);
        
        
        RegisterView ipcv = new RegisterView("intpc", machine.getIntpc());
        
        systemRegistersPanel.add(ipcv);
        
        
        RegisterView psrv = new RegisterView("psr", machine.getPsr());
        
        systemRegistersPanel.add(psrv);
        
        
        RegisterView intr = new RegisterView("intr", machine.getIntr());
        
        systemRegistersPanel.add(intr);
        
        
        RegisterView ptbr = new RegisterView("ptbr", machine.getPtbr());
        
        systemRegistersPanel.add(ptbr);
        
        
        RegisterView ioaddr = new RegisterView("ioaddr", machine.getIoaddr());
        
        systemRegistersPanel.add(ioaddr);
        
        
       
    }

    
    private void initDevicesMenu() {
        for (DeviceFactory factory: DeviceFactory.factories) {
            
            
            JMenuItem item = new JMenuItem(factory.getName());
            item.addActionListener(e -> {
                
                Device dev = factory.newDevice();
                machine.getIo().addDevice(dev);
                factory.newWindow(dev).setVisible(true);
                
                
            });
            addDeviceMenu.add(item);
        }
    }
    
    protected volatile Machine machine;
    protected MemoryWindow memWindow;

    private void changeState(PropertyChangeEvent e) {
        if (e.getPropertyName() != "state") {
            return;
        }
        
        switch ((Machine.State)e.getNewValue()) {
            case IDLE:
                bootButton.setEnabled(false);
                bootSettingsButton.setEnabled(false);
                stepButton.setEnabled(true);
                runButton.setEnabled(true);
                pauseButton.setEnabled(false);
                stopButton.setEnabled(true);
                break;
                
            case RUNNING:
                runButton.setEnabled(false);
                stepButton.setEnabled(false);
                pauseButton.setEnabled(true);
                break;
                
                
            case STOPPED:
                bootButton.setEnabled(true);
                bootSettingsButton.setEnabled(true);
                stepButton.setEnabled(false);
                runButton.setEnabled(false);
                pauseButton.setEnabled(false);
                stopButton.setEnabled(false);
                break;
        }
    }



}
